import type { Metadata } from "next";
import localFont from "next/font/local";
import { ChatbotInterfaceComponent } from "@/components/chatbot-interface";
import { ScrollArea } from "@/components/ui/scroll-area";
import { LandingPageComponent } from "@/components/landing-page";
import { RubiksCubeTutorialComponent } from "@/components/rubiks-cube-tutorial";
// import { Input } from "@/components/ui/input";
// import { Button } from "@/components/ui/button";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Coach Cash",
  description: "Generated by CC",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ChatbotInterfaceComponent />
        <ScrollArea>
        </ScrollArea>
        <LandingPageComponent />
        <RubiksCubeTutorialComponent/>
        {/* {children} */}
      </body>
    </html>
  );
}